name: simpledictionary
description: "A simple dictionary application."
publish_to: "none"
repository: "https://github.com/CrystalNetwork-Studio/SimpleDictionary"
issue_tracker: "https://github.com/CrystalNetwork-Studio/SimpleDictionary/issues"
version: 0.1.6

platforms:
  android:
  ios:

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.8
  cupertino_icons: ^1.0.8
  provider: ^6.0.0 # For state management
  path_provider: ^2.0.0 # For finding the documents directory
  path: ^1.8.0 # For path manipulation
  json_annotation: ^4.8.0 # For JSON serialization annotations
  shared_preferences: ^2.0.0 # Storing settings
  package_info_plus: ^8.3.0 # For getting app info
  url_launcher: ^6.3.1 # For opening URLs
  file_picker: ^10.0.0 # For picking files
  permission_handler: ^12.0.0+1 # For handling permissions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true
