name: simpledictionary
description: "A simple dictionary application."
publish_to: "none"

version: 0.1.0+1
platforms:
  android:
  ios:

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0 # For state management
  path_provider: ^2.0.0 # For finding the documents directory
  json_annotation: ^4.8.0 # For JSON serialization annotations
  shared_preferences: ^2.0.0 # Storing settings

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
flutter:
  uses-material-design: true
